name: Build and deploy Python app to Azure Web App - AltFleetInsightCanada

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make startup script executable
        run: chmod +x startup.sh

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*.git*" "venv/*" "node_modules/*" "*.log"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CLIENT_SECRET }}
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_14B681F27FEF4A6BADAB9E891FE8971C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_97002CDADE1E4818AF9F007F88D2AEE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D544B2A9D4484A57A3E28C144BE3139A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'AltFleetInsightCanada'
          slot-name: 'production'
          package: .
